spring:
  application:
    name: eureka-server
  # cloud:
  #   discovery:
  #     client:
  #       service-url:
  #         default: http://localhost:8761/eureka/
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    # server:
    #   enable-self-preservation: false
    #   eviction-interval-timer-in-ms: 10000
    #   response-cache-update-interval-ms: 10000
    #   prefer-ip-address: true
    #   enable-async-status-updates: true
    #   enable-async-status-updates-interval-in-ms: 10000 
server:
  port: 8761
